#!/bin/bash
#create by yaoyao

DBNAME=C#P1
DBUSER=C#P2
DBPWD=C#P3
BKPATH=C#P4
SQLFILENAME=C#P5
DBHOST=C#P6

CURPWD=`pwd`
mkdir -p $BKPATH
cd $BKPATH

if [ -z $DBPWD ]; then
  mysqldump -u$DBUSER -h$DBHOST --skip-opt --no-create-info --extended-insert=false --complete-insert --add-locks --create-options --disable-keys --quick --triggers=false --hex-blob $DBNAME auction battle cashexrecord chargerecord creaturemix diamondsale frdintimity gmcmd goldsale ibpayuserecord mails npc npcmaprelation npcrelation offlineop playerbattleinfo point_5 point_43 question require rolesdead rolesdelete rolesfirst rolesrename rolessecond sign society societymem societyopinfo treasurebowl > $SQLFILENAME
else
  mysqldump -u$DBUSER -p$DBPWD -h$DBHOST --skip-opt --no-create-info --extended-insert=false --complete-insert --add-locks --create-options --disable-keys --quick --triggers=false --hex-blob $DBNAME auction battle cashexrecord chargerecord creaturemix diamondsale frdintimity gmcmd goldsale ibpayuserecord mails npc npcmaprelation npcrelation offlineop playerbattleinfo point_5 point_43 question require rolesdead rolesdelete rolesfirst rolesrename rolessecond sign society societymem societyopinfo treasurebowl > $SQLFILENAME
fi

cd $CURPWD
